### ISSUE TITLE
改哪个参数可以让下载的文件保存到指定的文件夹

### ISSUE THREAD

**Issue by zx2021** [Jittor/JittorLLMs#12]
如题，以及有什么办法可以用原装的torch吗（实在不想改来改去了）

**Comment by zjp-shadow** [comment]
你好，修改路径的方法可以参考 #17 ，目前不能使用原装的torch，因为jtorch的实现方法是将torch相应的算子替换为jittor实现的版本，所以目前推荐用conda新建一个环境来运行JittorLLMs的框架
