### ISSUE TITLE
是否支持AMD Radeon(TM) Graphics这种集成显卡？

### ISSUE THREAD

**Issue by e8-YanjingHao** [Jittor/JittorLLMs#13]
跑起来后4G得显存看着没有用上，是否不支持这种集成显卡?

**Comment by e8-YanjingHao** [comment]
mpicc not found, distribution disabled

启动时会看到一个这个提示，不知是否有影响

**Comment by zjp-shadow** [comment]
你好， 1.集显似乎并没有支持ROCm，所以并不能用于深度学习计算，所以您的环境可能只能使用cpu进行推理；2.第二个问题不影响运行效率，mpi是用于支持多卡的并行框架。

**Comment by e8-YanjingHao** [comment]
> 你好， 1.集显似乎并没有支持ROCm，所以并不能用于深度学习计算，所以您的环境可能只能使用cpu进行推理；2.第二个问题不影响运行效率，mpi是用于支持多卡的并行框架。

明白了，谢谢
