### ISSUE TITLE
怎么修改模型下载位置

### ISSUE THREAD

**Issue by maxleton-cyber** [Jittor/JittorLLMs#145]
运行python cli_demo.py chatglm后，模型都会默认下载在C盘，C盘存储空间不够，我想修改下载位置应该怎么修改

**Comment by lcl101** [comment]
在cli.py添加以下代码：
import os

if __name__ == "__main__":
   os.environ.setdefault("JITTOR_HOME",r"F:/work/win/wf/py/gpt/JittorLLMs/model_cach")

**Comment by zxh126** [comment]
SET JITTOR_HOME=YOUR\NEW\PATH

**Comment by Qqgl** [comment]
> 在cli.py添加以下代码： import os
> 
> if **name** == "**main**": os.environ.setdefault("JITTOR_HOME",r"F:/work/win/wf/py/gpt/JittorLLMs/model_cach")
完整代码贴一下吧？


import argparse
import os

import models

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("model", choices=models.availabel_models)
    args = parser.parse_args()
    model = models.get_model(args)
    model.chat()

if name == "main":
    os.environ.setdefault("JITTOR_HOME", r"F:/work/win/wf/py/gpt/JittorLLMs/model_cach") 
是我这样嘛？
