### ISSUE TITLE
无法

### ISSUE THREAD

**Issue by seekyong** [Jittor/JittorLLMs#15]
![image](https://user-images.githubusercontent.com/11072899/229963982-004d7085-6b42-4479-8e2c-c98a0d705b84.png)

**Comment by seekyong** [comment]
按提示也更新过，没有用

**Comment by zjp-shadow** [comment]
你好，请问按照提示更新过后的报错是什么呢？

**Comment by aka-wen** [comment]
> 你好，请问按照提示更新过后的报错是什么呢？

Mac m1 16g
我的也是，更新之后运行也是一样的提示

**Comment by zjp-shadow** [comment]
> > 你好，请问按照提示更新过后的报错是什么呢？
> 
> Mac m1 16g 我的也是，更新之后运行也是一样的提示

你好，请问运行 `pyhon3 -m pip install -r models/chatglm/requirements.txt` 之后的错误信息是什么呢？还是缺少 `transformer` 这个库吗？

**Comment by aka-wen** [comment]
> > > 你好，请问按照提示更新过后的报错是什么呢？
> > 
> > 
> > Mac m1 16g 我的也是，更新之后运行也是一样的提示
> 
> 你好，请问运行 `pyhon3 -m pip install -r models/chatglm/requirements.txt` 之后的错误信息是什么呢？还是缺少 `transformer` 这个库吗？

是的

**Comment by aka-wen** [comment]
> ![image](https://user-images.githubusercontent.com/11072899/229963982-004d7085-6b42-4479-8e2c-c98a0d705b84.png)

可以试试python3 -> python ..

**Comment by zjp-shadow** [comment]
> > > > 你好，请问按照提示更新过后的报错是什么呢？
> > > 
> > > 
> > > Mac m1 16g 我的也是，更新之后运行也是一样的提示
> > 
> > 
> > 你好，请问运行 `pyhon3 -m pip install -r models/chatglm/requirements.txt` 之后的错误信息是什么呢？还是缺少 `transformer` 这个库吗？
> 
> 是的

请问现在用pip安装是可以的吗？`requirements.txt` 应该是有 `transformers` 这个库的。

**Comment by aka-wen** [comment]
> > > > > 你好，请问按照提示更新过后的报错是什么呢？
> > > > 
> > > > 
> > > > Mac m1 16g 我的也是，更新之后运行也是一样的提示
> > > 
> > > 
> > > 你好，请问运行 `pyhon3 -m pip install -r models/chatglm/requirements.txt` 之后的错误信息是什么呢？还是缺少 `transformer` 这个库吗？
> > 
> > 
> > 是的
> 
> 请问现在用pip安装是可以的吗？`requirements.txt` 应该是有 `transformers` 这个库的。

这个问题已经解决了，谢谢
