### ISSUE TITLE
能开放个接口改cache_dir吗？

### ISSUE THREAD

**Issue by qingquanlingyu** [Jittor/JittorLLMs#17]
C盘只剩5G的win用户落泪，CUDA都下载不完就满了
看了下源码，改cache_dir的环境变量，还是没有用
能不能给个参数接口啊😢

**Comment by zjp-shadow** [comment]
可以改的，用set JITTOR_HOME=your_path就可以修改jittor全局的环境变量，也可以通过修改环境变量中的cache_path的路径来解决。
可以参考一下https://discuss.jittor.org/t/topic/98
