### ISSUE TITLE
提问：如何恢复jittor框架之前的安装环境？

### ISSUE THREAD

**Issue by qingfengtommy** [Jittor/JittorLLMs#25]
您好！
我创建并激活了一个新的环境用于安装jittor,

`conda create -n jittor `
`conda activate jittor `
并在环境中运行
`git clone https://github.com/Jittor/JittorLLMs.git --depth 1`
`cd JittorLLMs`
`pip install -r requirements.txt -i https://pypi.jittor.org/simple -I`

现在当我切换回base环境时，运行别的项目代码时仍然是基于jittor框架的
请问该如何解决呢？

**Comment by zjp-shadow** [comment]
你好？请问在 `base` 环境中运行 `pip show jtorch` 的结果是什么呢？

**Comment by qingfengtommy** [comment]
> 
您好， 
运行` pip show jtorch`后
目前是这样的：
```

Name: jtorch
Version: 0.1.3
Summary: jtorch project
Home-page: https://github.com/JITTorch/jtorch
Author: jtorch
Author-email: jtorch@qq.com
License:
Location: d:\users\tommy\anaconda3\lib\site-packages
Requires: jittor, requests
Required-by:
```

**Comment by zjp-shadow** [comment]
> > 
> 
> 您好， 运行` pip show jtorch`后 目前是这样的：
> 
> ```
> 
> Name: jtorch
> Version: 0.1.3
> Summary: jtorch project
> Home-page: https://github.com/JITTorch/jtorch
> Author: jtorch
> Author-email: jtorch@qq.com
> License:
> Location: d:\users\tommy\anaconda3\lib\site-packages
> Requires: jittor, requests
> Required-by:
> ```

您好，那您可能错误的将 `jtorch` 安装到了 `base` 环境中，可以尝试用 `pip uninstall jtorch` 从初始环境中卸载。

**Comment by qingfengtommy** [comment]
> > > 
> > 
> > 
> > 您好， 运行` pip show jtorch`后 目前是这样的：
> > ```
> > 
> > Name: jtorch
> > Version: 0.1.3
> > Summary: jtorch project
> > Home-page: https://github.com/JITTorch/jtorch
> > Author: jtorch
> > Author-email: jtorch@qq.com
> > License:
> > Location: d:\users\tommy\anaconda3\lib\site-packages
> > Requires: jittor, requests
> > Required-by:
> > ```
> 
> 您好，那您可能错误的将 `jtorch` 安装到了 `base` 环境中，可以尝试用 `pip uninstall jtorch` 从初始环境中卸载。

好的，谢谢您！
