### ISSUE TITLE
请问：每次提问都报错，麻烦您看下啥原因

### ISSUE THREAD

**Issue by shampooX** [Jittor/JittorLLMs#28]
配置很低 o(╥﹏╥)o ，rx5600 + gtx960 2g + 8g内存
![1](https://user-images.githubusercontent.com/37948073/230433379-e78ea2de-ff1a-49ba-a51f-28a61c69338e.png)
![2](https://user-images.githubusercontent.com/37948073/230433416-39dbf0db-4bc5-4c7c-ae7a-4105f9c945bd.png)

**Comment by Jittor** [comment]
设置环境变量nvcc_path=””试试，$env:nvcc_path=''



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月6日(周四) 晚上11:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Jittor/JittorLLMs] 请问：每次提问都报错，麻烦您看下啥原因 (Issue #28)




 
配置很低 o(╥﹏╥)o ，rx5600 + gtx960 2g + 8g内存

**Comment by shampooX** [comment]
还是报错了
![3](https://user-images.githubusercontent.com/37948073/230439176-ee0896e4-8b7f-4550-beaa-c47b5382122b.png)
![4](https://user-images.githubusercontent.com/37948073/230439198-e29096c7-1b60-41da-86f3-4e0f2c30d8fb.png)

**Comment by Exusial** [comment]
python太新了？可以换python3.10及以下版本试试？
