### ISSUE TITLE
设置显存的使用量但还是爆显存，怀疑是不是读库出问题

### ISSUE THREAD

**Issue by weixingrui** [Jittor/JittorLLMs#53]
[i 0421 15:24:03.376000 76 compile_extern.py:522] mpicc not found, distribution disabled.
[w 0421 15:24:03.437000 76 compile_extern.py:203] CUDA related path found in LD_LIBRARY_PATH or PATH(['', 'C', '\\Users\\thunderobot\\.cache\\jittor\\jtcuda\\cuda11.2_cudnn8_win\\lib64', '', 'C', '\\Users\\thunderobot\\.cache\\jittor\\mkl\\dnnl_win_2.2.0_cpu_vcomp\\bin', '', 'C', '\\Users\\thunderobot\\.cache\\jittor\\mkl\\dnnl_win_2.2.0_cpu_vcomp\\lib', '', 'C', '\\Users\\thunderobot\\.cache\\jittor\\jt1.3.7\\cl\\py3.9.0\\Windows-10-10.x38\\AMDRyzen75800Hxb1\\default', '', 'C', '\\Users\\thunderobot\\.cache\\jittor\\jt1.3.7\\cl\\py3.9.0\\Windows-10-10.x38\\AMDRyzen75800Hxb1\\default\\cu11.2.67', '', 'C', '\\Users\\thunderobot\\.cache\\jittor\\jtcuda\\cuda11.2_cudnn8_win\\bin', '', 'C', '\\Users\\thunderobot\\.cache\\jittor\\jtcuda\\cuda11.2_cudnn8_win\\lib\\x64', '', 'C', '\\Users\\thunderobot\\.cache\\jittor\\msvc\\win10_kits\\lib\\ucrt\\x64', '', 'C', '\\Users\\thunderobot\\.cache\\jittor\\msvc\\win10_kits\\lib\\um\\x64', '', 'C', '\\Users\\thunderobot\\.cache\\jittor\\msvc\\VC\\lib', '', 'c', '\\users\\thunderobot\\appdata\\local\\programs\\python\\python39\\libs', 'C', '\\Users\\thunderobot\\.cache\\jittor\\msvc\\VC\\_\\_\\_\\_\\_\\bin', 'C', '\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\bin', 'C', '\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\libnvvp', 'C', '\\Windows\\system32', 'C', '\\Windows', 'C', '\\Windows\\System32\\Wbem', 'C', '\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C', '\\Windows\\System32\\OpenSSH\\', 'C', '\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common', 'C', '\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR', 'D', '\\matlab\\runtime\\win64', 'D', '\\matlab\\bin', 'D', '\\matlab\\polyspace\\bin', 'D', '\\LINGO64_18\\', 'C', '\\Program Files\\NVIDIA Corporation\\Nsight Compute 2023.1.0\\', 'D', '\\Git\\cmd', 'D', '\\New Folder\\', 'C', '\\Users\\thunderobot\\miniconda3\\pkgs\\python-3.9.16-h6244533_2\\chromedriver.exe', '', '%SystemRoot%\\system32', '%SystemRoot%', '%SystemRoot%\\System32\\Wbem', '%SYSTEMROOT%\\System32\\WindowsPowerShell\\v1.0\\', '%SYSTEMROOT%\\System32\\OpenSSH\\', 'C', '\\Users\\thunderobot\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\', 'C', '\\Users\\thunderobot\\AppData\\Local\\Programs\\Python\\Python39\\', 'C', '\\Users\\thunderobot\\AppData\\Local\\Microsoft\\WindowsApps', 'C', '\\Program Files\\JetBrains\\PyCharm Community Edition 2020.2.4\\bin', '', 'C', '\\Users\\thunderobot\\AppData\\Roaming\\npm', 'C', '\\Users\\thunderobot\\miniconda3\\pkgs\\python-3.9.16-h6244533_2\\chromedriver.exe', '']), This path may cause jittor found the wrong libs, please unset LD_LIBRARY_PATH and remove cuda lib path in Path.
Or you can let jittor install cuda for you: `python3.x -m jittor_utils.install_cuda`

**Comment by TanYufei** [comment]
same error
