### ISSUE TITLE
windows如何修改缓存文件夹

### ISSUE THREAD

**Issue by zyuerugou** [Jittor/JittorLLMs#59]
默认在C:\\Users\User\.cache下，我希望把他放到别的盘符下

**Comment by Sqhttwl** [comment]
> 默认在C:\\Users\User\.cache下，我希望把他放到别的盘符下

我也遇到这个问题了哈哈😄

**Comment by Sqhttwl** [comment]
解决方案是：$env:JITTOR="路径"

**Comment by DrayChou** [comment]
https://github.com/Jittor/JittorLLMs#%E9%85%8D%E7%BD%AE%E8%A6%81%E6%B1%82
這裏有寫
`磁盘空间不够时，可以通过环境变量JITTOR_HOME指定缓存存放路径。`

**Comment by TcDhlPro** [comment]
在你的项目虚拟环境中执行`pip install python-dotenv`
然后在你的项目根目录, 也就是与虚拟环境目录同级的目录下, 创建一个文件`.env`
然后在`.env`这个文件中添加`JITTOR_HOME="D:\\YouPathPwd"`

**Comment by zyuerugou** [comment]
我是在anaconda prompt中指定env然后可以执行
`
conda activate chatGLM-6B-JittorLLMs
f:
cd workSpace\JittorHome\
$Env:JITTOR_HOME="F:\workSpace\JittorHome\"
$Env:JT_SAVE_MEM="1"
$Env:cpu_mem_limit="24000000000"
$Env:device_mem_limit="7500000000"
D:/Anaconda3/envs/chatGLM-6B-JittorLLMs/python.exe f:/workSpace/JittorLLMs-main/cli_demo.py chatglm
`
