### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.utils.hooks'

### ISSUE THREAD

**Issue by BasicAILinDu** [Jittor/JittorLLMs#62]
Import Error, maybe the dependencies are not installed, please try 'python -m pip install -r models/chatglm/requirements.txt -i https://pypi.jittor.org/simple'
导入错误，可能没有安装此模型需要的依赖，请尝试运行 'python -m pip install -r models/chatglm/requirements.txt -i https://pypi.jittor.org/simple'

**Comment by johnlui** [comment]
我也遇到这个问题了

**Comment by johnlui** [comment]
我解决了这个问题，把 accelerate 卸载了就行：

```bash
pip uninstall accelerate
```

**Comment by yaleimeng** [comment]
@johnlui   多谢！确实有效。

**Comment by HJT9328** [comment]
多谢 有效

> 我解决了这个问题，把 accelerate 卸载了就行：
> 
> ```shell
> pip uninstall accelerate
> ```

多谢  有效

**Comment by StoneRen** [comment]
> 

有效

**Comment by RavenHuo** [comment]
解决了，牛的

**Comment by Micraow** [comment]
我在卸载后遇到：

ModuleNotFoundError: No module named 'accelerate'
