### ISSUE TITLE
能否支持langchain？

### ISSUE THREAD

**Issue by liunux4odoo** [Jittor/JittorLLMs#72]
首先感谢作者，让我们消费级机器也能顺利的跑大模型。我的机器是16g内存＋6g显存，跑jittorllm＋chatglm基本没有爆过显存，处理一个prompt不到十分钟。

直接微调chatglm太费劲了，有没有考虑支持langchain，直接外挂知识库？

**Comment by dalecgu** [comment]
使用C-S架构，服务端使用JittorLLMs的api.py，客户端用langchain[自定义一个LLM](https://python.langchain.com/en/latest/modules/models/llms/examples/custom_llm.html)去请求api。外挂知识库之类的逻辑都可以放在客户端里，想怎么实现都行。

**Comment by liunux4odoo** [comment]
> 使用C-S架构，服务端使用JittorLLMs的api.py，客户端用langchain[自定义一个LLM](https://python.langchain.com/en/latest/modules/models/llms/examples/custom_llm.html)去请求api。外挂知识库之类的逻辑都可以放在客户端里，想怎么实现都行。

我的意思是能不能把langchain也用动态内存改造一下，毕竟langchain最低也要3G左右的显存

**Comment by cty080505** [comment]
langchain用了sentence_transformers，但这个库调用了大量jtorch未提供的接口，改造很麻烦，我就直接用C-S了。

**Comment by liunux4odoo** [comment]
> langchain用了sentence_transformers，但这个库调用了大量jtorch未提供的接口，改造很麻烦，我就直接用C-S了。

那就用API模式了

**Comment by Crescentz** [comment]
请问现在的代码支持 知识库吗，如何使用
