### ISSUE TITLE
python cli_demo.py chatglm 命令报错

### ISSUE THREAD

**Issue by e8-YanjingHao** [Jittor/JittorLLMs#8]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\JittorLLMs\JittorLLMs\cli_demo.py", line 8, in <module>
    model = models.get_model(args)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\JittorLLMs\JittorLLMs\models\__init__.py", line 38, in get_model
    globals()[f"get_{model_name}"]()
  File "D:\Projects\JittorLLMs\JittorLLMs\models\util.py", line 51, in get_chatglm
    new_path.append(download_fromhub(f"jittorhub://{f}", tdir="chat-glm"))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\JittorLLMs\JittorLLMs\models\util.py", line 5, in download_fromhub
    import jittor as jt
  File "C:\Python311\Lib\site-packages\jittor\__init__.py", line 18, in <module>
    from . import compiler
  File "C:\Python311\Lib\site-packages\jittor\compiler.py", line 1356, in <module>
    compile(cc_path, cc_flags+opt_flags, files, 'jittor_core'+extension_suffix)
  File "C:\Python311\Lib\site-packages\jittor\compiler.py", line 151, in compile
    jit_utils.run_cmds(cmds, cache_path, jittor_path, "Compiling "+base_output)
  File "C:\Python311\Lib\site-packages\jittor_utils\__init__.py", line 251, in run_cmds
    for i,_ in enumerate(p.imap_unordered(do_compile, cmds)):
  File "C:\Python311\Lib\multiprocessing\pool.py", line 873, in next
    raise value
RuntimeError: [f 0404 16:41:33.781000 36 log.cc:608] Check failed ret(2) == 0(0) Run cmd failed: "C:\Users\Yanjing\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe" "c:\python311\lib\site-packages\jittor\src\pybind\py_var_tracer.cc"   -std:c++17        -EHa -MD -utf-8  -nologo -I"C:\Users\Yanjing\.cache\jittor\msvc\VC\include" -I"C:\Users\Yanjing\.cache\jittor\msvc\win10_kits\include\ucrt" -I"C:\Users\Yanjing\.cache\jittor\msvc\win10_kits\include\shared" -I"C:\Users\Yanjing\.cache\jittor\msvc\win10_kits\include\um" -DNOMINMAX   -I"c:\python311\lib\site-packages\jittor\src" -I"c:\python311\include" -I"C:\Users\Yanjing\.cache\jittor\jt1.3.7\cl\py3.11.0\Windows-10-10.x4a\AMDRyzen75800Hxb1\default"   -O2   -c -Fo: "C:\Users\Yanjing\.cache\jittor\jt1.3.7\cl\py3.11.0\Windows-10-10.x4a\AMDRyzen75800Hxb1\default\obj_files\py_var_tracer.cc.obj"

**Comment by e8-YanjingHao** [comment]
系统 win11 家庭中文版

**Comment by e8-YanjingHao** [comment]
I have updated jittor to 1.3.7.4， jtorch to 0.1.3

**Comment by cjld** [comment]
您好，您尝试更新jittor到`1.3.7.5`试试

**Comment by e8-YanjingHao** [comment]
> 您好，您尝试更新 jittor 到 `1.3.7.5` 试试

谢谢，现在是下载完模型后报这个错误

python cli_demo.py chatglm
[i 0404 21:44:00.875000 88 compiler.py:955] Jittor(1.3.7.5) src: c:\python311\lib\site-packages\jittor
[i 0404 21:44:00.892000 88 compiler.py:956] cl at C:\Users\Yanjing\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 0404 21:44:00.892000 88 compiler.py:957] cache_path: C:\Users\Yanjing\.cache\jittor\jt1.3.7\cl\py3.11.0\Windows-10-10.x4a\AMDRyzen75800Hxb1\default
[i 0404 21:44:00.940000 88 __init__.py:227] Total mem: 27.87GB, using 9 procs for compiling.
[i 0404 21:44:01.564000 88 jit_compiler.cc:28] Load cc_path: C:\Users\Yanjing\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe
[i 0404 21:44:01.683000 88 compile_extern.py:522] mpicc not found, distribution disabled.
'ln' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'ln' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'ln' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'ln' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'ln' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'ln' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'ln' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'ln' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards:   0%|                                                                                                                                     | 0/8 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\transformers\modeling_utils.py", line 415, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\jtorch\__init__.py", line 228, in load
    return jt.load(path)
           ^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\jittor\__init__.py", line 1124, in load
    model_dict = safeunpickle(path)
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\jittor\__init__.py", line 98, in safeunpickle
    model_dict = load_pytorch(path)
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\jittor_utils\load_pytorch.py", line 224, in load_pytorch
    f = open(fn_name, "rb")
        ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Projects\\JittorLLMs\\JittorLLMs\\models\\chatglm\\pytorch_model-00001-of-00008.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\JittorLLMs\JittorLLMs\cli_demo.py", line 8, in <module>
    model = models.get_model(args)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\JittorLLMs\JittorLLMs\models\__init__.py", line 42, in get_model
    return module.get_model(args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\JittorLLMs\JittorLLMs\models\chatglm\__init__.py", line 40, in get_model
    return ChatGLMMdoel(args)
           ^^^^^^^^^^^^^^^^^^
  File "D:\Projects\JittorLLMs\JittorLLMs\models\chatglm\__init__.py", line 20, in __init__
    self.model = AutoModel.from_pretrained(os.path.dirname(__file__), trust_remote_code=True).half().cuda()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\transformers\models\auto\auto_factory.py", line 459, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\transformers\modeling_utils.py", line 2478, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\transformers\modeling_utils.py", line 2780, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\transformers\modeling_utils.py", line 418, in load_state_dict
    with open(checkpoint_file) as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Projects\\JittorLLMs\\JittorLLMs\\models\\chatglm\\pytorch_model-00001-of-00008.bin'

**Comment by Angusvencent** [comment]
> 经过尝试，需要手动安装sentencepiece，cygwin64
> 
> 并再cygwin中跑 python cli_demo.py chatglm
> 
> 成功跑成功一次后，即可在普通cmd中成功运行 python cli_demo.py chatglm


请问怎么手动安装sentencepiece, cygwin64呀？pip install 一直安装不上。
报错：
Collecting sentencepiece
  Using cached sentencepiece-0.1.97.tar.gz (524 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: sentencepiece
  Building wheel for sentencepiece (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\sentencepiece
      copying src\sentencepiece/__init__.py -> build\lib.win-amd64-cpython-311\sentencepiece
      copying src\sentencepiece/_version.py -> build\lib.win-amd64-cpython-311\sentencepiece
      copying src\sentencepiece/sentencepiece_model_pb2.py -> build\lib.win-amd64-cpython-311\sentencepiece
      copying src\sentencepiece/sentencepiece_pb2.py -> build\lib.win-amd64-cpython-311\sentencepiece
      running build_ext
      building 'sentencepiece._sentencepiece' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\src
      creating build\temp.win-amd64-cpython-311\Release\src\sentencepiece
...........
.............
      cl: 命令行 warning D9025 :正在重写“/MD”(用“/MT”)
      sentencepiece_wrap.cxx
      src/sentencepiece/sentencepiece_wrap.cxx(2822): fatal error C1083: 无法打开包括文件: “sentencepiece_processor.h”: No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sentencepiece
  Running setup.py clean for sentencepiece
Failed to build sentencepiece
Installing collected packages: sentencepiece
  Running setup.py install for sentencepiece ... error
  error: subprocess-exited-with-error

  × Running setup.py install for sentencepiece did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running install
.............
..............
      cl: 命令行 warning D9025 :正在重写“/MD”(用“/MT”)
      sentencepiece_wrap.cxx
      src/sentencepiece/sentencepiece_wrap.cxx(2822): fatal error C1083: 无法打开包括文件: “sentencepiece_processor.h”: No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> sentencepiece

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by e8-YanjingHao** [comment]
> > 经过尝试，需要手动安装 sentencepiece，cygwin64
> > 并再 cygwin 中跑 python cli_demo.py chatglm
> > 成功跑成功一次后，即可在普通 cmd 中成功运行 python cli_demo.py chatglm
> 
> 请问怎么手动安装 sentencepiece, cygwin64 呀？pip install 一直安装不上。 报错： Collecting sentencepiece Using cached sentencepiece-0.1.97.tar.gz (524 kB) Preparing metadata (setup.py) ... done Building wheels for collected packages: sentencepiece Building wheel for sentencepiece (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [21 lines of output] running bdist_wheel running build running build_py creating build creating build\lib.win-amd64-cpython-311 creating build\lib.win-amd64-cpython-311\sentencepiece copying src\sentencepiece/**init**.py -> build\lib.win-amd64-cpython-311\sentencepiece copying src\sentencepiece/_version.py -> build\lib.win-amd64-cpython-311\sentencepiece copying src\sentencepiece/sentencepiece_model_pb2.py -> build\lib.win-amd64-cpython-311\sentencepiece copying src\sentencepiece/sentencepiece_pb2.py -> build\lib.win-amd64-cpython-311\sentencepiece running build_ext building 'sentencepiece._sentencepiece' extension creating build\temp.win-amd64-cpython-311 creating build\temp.win-amd64-cpython-311\Release creating build\temp.win-amd64-cpython-311\Release\src creating build\temp.win-amd64-cpython-311\Release\src\sentencepiece ........... ............. cl: 命令行 warning D9025 : 正在重写 “/MD”(用 “/MT”) sentencepiece_wrap.cxx src/sentencepiece/sentencepiece_wrap.cxx (2822): fatal error C1083: 无法打开包括文件: “sentencepiece_processor.h”: No such file or directory error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe' failed with exit code 2 [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for sentencepiece Running setup.py clean for sentencepiece Failed to build sentencepiece Installing collected packages: sentencepiece Running setup.py install for sentencepiece ... error error: subprocess-exited-with-error
> 
> × Running setup.py install for sentencepiece did not run successfully. │ exit code: 1 ╰─> [23 lines of output] running install ............. .............. cl: 命令行 warning D9025 : 正在重写 “/MD”(用 “/MT”) sentencepiece_wrap.cxx src/sentencepiece/sentencepiece_wrap.cxx (2822): fatal error C1083: 无法打开包括文件: “sentencepiece_processor.h”: No such file or directory error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe' failed with exit code 2 [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure
> 
> × Encountered error while trying to install package. ╰─> sentencepiece
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure.

你的python是3.11版本吗？是的话用这个安装
[sentencepiece-0.1.98-cp311-cp311-win_amd64.zip](https://github.com/Jittor/JittorLLMs/files/11165356/sentencepiece-0.1.98-cp311-cp311-win_amd64.zip)

下载解压后
pip install xxx.whl

**Comment by cjld** [comment]
我跑windows似乎不需要安装 sentencepiece，cygwin64，您吧`jittorLLMs`也更新到最新版本试试？
