### ISSUE TITLE
cuda 错误。 成功运行之后，提问出现如下报错 

### ISSUE THREAD

**Issue by wwjCMP** [Jittor/JittorLLMs#80]
Traceback (most recent call last):
  File "I:\JittorLLMs\cli_demo.py", line 9, in <module>
    model.chat()
  File "I:\JittorLLMs\models\chatglm\__init__.py", line 36, in chat
    for response, history in self.model.stream_chat(self.tokenizer, text, history=history):
  File "C:\Users\wwj93/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 1259, in stream_chat
    for outputs in self.stream_generate(**input_ids, **gen_kwargs):
  File "C:\Users\wwj93/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 1336, in stream_generate
    outputs = self(
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\jtorch\nn\__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "C:\Users\wwj93/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 1138, in forward
    transformer_outputs = self.transformer(
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\jtorch\nn\__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "C:\Users\wwj93/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 973, in forward
    layer_ret = layer(
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\jtorch\nn\__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "C:\Users\wwj93/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 614, in forward
    attention_outputs = self.attention(
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\jtorch\nn\__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "C:\Users\wwj93/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 454, in forward
    cos, sin = self.rotary_emb(q1, seq_len=position_ids.max() + 1)
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\jtorch\nn\__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "C:\Users\wwj93/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 202, in forward
    t = torch.arange(seq_len, device=x.device, dtype=self.inv_freq.dtype)
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\jtorch\__init__.py", line 31, in inner
    ret = func(*args, **kw)
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\jittor\misc.py", line 809, in arange
    if isinstance(start, jt.Var): start = start.item()
RuntimeError: [f 0429 08:52:48.542000 44 executor.cc:682]
Execute fused operator(12/43) failed.
[JIT Source]: C:\Users\wwj93\.cache\jittor\jt1.3.7\cl\py3.9.16\Windows-10-10.x0e\IntelRCoreTMi7x56\default\cu11.2.67\jit\__opkey0_broadcast_to__Tx_float16__DIM_3__BCAST_1__opkey1_broadcast_to__Tx_float16__DIM_3____hash_9730a00665a5a466_op.cc
[OP TYPE]: fused_op:( broadcast_to, broadcast_to, binary.multiply, reduce.add,)
[Input]: float16[4096,4096,]transformer.layers.11.attention.dense.weight, float16[8,4096,],
[Output]: float16[8,4096,],
[Async Backtrace]: not found, please set env JT_SYNC=1, trace_py_var=3
[Reason]: [f 0429 08:52:48.541000 44 helper_cuda.h:128] CUDA error at c:\users\wwj93\anaconda3\envs\jittor\lib\site-packages\jittor\src\mem\allocator\cuda_device_allocator.cc:33  code=2( cudaErrorMemoryAllocation ) cudaMallocManaged(&ptr, size)
**********
Async error was detected. To locate the async backtrace and get better error report, please rerun your code with two enviroment variables set:
cmd:
>>> set JT_SYNC=1
>>> set trace_py_var=3
powershell:
>>> $env:JT_SYNC=1
>>> $env:trace_py_var=3

**Comment by wwjCMP** [comment]
RuntimeError: [f 0429 08:56:11.744000 76 executor.cc:682]
Execute fused operator(12/43) failed.
[JIT Source]: C:\Users\wwj93\.cache\jittor\jt1.3.7\cl\py3.9.16\Windows-10-10.x0e\IntelRCoreTMi7x56\default\cu11.2.67\jit\__opkey0_broadcast_to__Tx_float16__DIM_3__BCAST_1__opkey1_broadcast_to__Tx_float16__DIM_3____hash_9730a00665a5a466_op.cc
[OP TYPE]: fused_op:( broadcast_to, broadcast_to, binary.multiply, reduce.add,)
[Input]: float16[4096,4096,]transformer.layers.11.attention.dense.weight, float16[4,4096,],
[Output]: float16[4,4096,],
[Async Backtrace]: not found, please set env JT_SYNC=1, trace_py_var=3
[Reason]: [f 0429 08:56:11.740000 76 helper_cuda.h:128] CUDA error at c:\users\wwj93\anaconda3\envs\jittor\lib\site-packages\jittor\src\mem\allocator\cuda_device_allocator.cc:33  code=2( cudaErrorMemoryAllocation ) cudaMallocManaged(&ptr, size)

**Comment by wwjCMP** [comment]
运行时，GPU几乎不工作，1060 6G的显卡

**Comment by wwjCMP** [comment]
[i 0429 08:59:35.508000 16 cuda_flags.cc:39] CUDA enabled.
用户输入:hello
[w 0429 09:00:15.731000 16 cuda_device_allocator.cc:30] Unable to alloc cuda device memory, use unify memory instead. This may cause low performance.
[i 0429 09:00:15.732000 16 cuda_device_allocator.cc:32]
=== display_memory_info ===
 total_cpu_ram:    15 B total_device_ram:     6GB
 hold_vars: 445 lived_vars: 554 lived_ops: 135
 jtorch_grad_vars: 0
 name: sfrl is_device: 1 used: 5.369GB(100%) unused: 1.167MB(0.0212%) total:  5.37GB
 name: sfrl is_device: 1 used:     0 B(0%) unused:     1MB(100%) total:     1MB
 name: sfrl is_device: 0 used:     0 B(0%) unused:     1MB(100%) total:     1MB
 name: sfrl is_device: 0 used: 7.431GB(58.1%) unused: 5.369GB(41.9%) total:  12.8GB
 name: temp is_device: 0 used:     0 B(-nan(ind)%) unused:     0 B(-nan(ind)%) total:     0 B
 name: temp is_device: 1 used:     0 B(-nan(ind)%) unused:     0 B(-nan(ind)%) total:     0 B
 cpu&gpu: 18.17GB gpu: 5.371GB cpu:  12.8GB
 free: cpu(    0 B) gpu(    0 B)
 swap: total(    0 B) last(    0 B)
===========================

[w 0429 09:00:16.606000 16 cuda_device_allocator.cc:30] Unable to alloc cuda device memory, use unify memory instead. This may cause low performance.
[i 0429 09:00:16.643000 16 cuda_device_allocator.cc:32]
=== display_memory_info ===
 total_cpu_ram:    15 B total_device_ram:     6GB
 hold_vars: 445 lived_vars: 554 lived_ops: 135
 jtorch_grad_vars: 0
 name: sfrl is_device: 1 used: 5.369GB(100%) unused: 1.167MB(0.0212%) total:  5.37GB
 name: sfrl is_device: 1 used:     0 B(0%) unused:     1MB(100%) total:     1MB
 name: sfrl is_device: 0 used:     0 B(0%) unused:     1MB(100%) total:     1MB
 name: sfrl is_device: 0 used: 7.431GB(58.1%) unused: 5.369GB(41.9%) total:  12.8GB
 name: temp is_device: 0 used:     0 B(-nan(ind)%) unused:     0 B(-nan(ind)%) total:     0 B
 name: temp is_device: 1 used:     0 B(-nan(ind)%) unused:     0 B(-nan(ind)%) total:     0 B
 cpu&gpu: 18.17GB gpu: 5.371GB cpu:  12.8GB
 free: cpu(    0 B) gpu(    0 B)
 swap: total(    0 B) last(    0 B)
===========================

**Comment by linkerlin** [comment]
看起来是显存不足

**Comment by bhzhu203** [comment]
export JT_SAVE_MEM=1
# 限制cpu最多使用16G
export cpu_mem_limit=16000000000
# 限制device内存（如gpu、tpu等）最多使用8G
export device_mem_limit=8000000000
# windows 用户，请使用powershell
# $env:JT_SAVE_MEM="1"
# $env:cpu_mem_limit="16000000000"
# $env:device_mem_limit="8000000000"

需要知道你目前显存是多少 然后限制一下就行 最重要的是“export JT_SAVE_MEM=1” 这个一定要设置！

**Comment by venxzw** [comment]
![4DPXG4UI5@bhzhu203 您好，我想请问以下，我全部都设置了运行后还是出现了如下错误：
HBGZ8$_2HKT1](https://github.com/Jittor/JittorLLMs/assets/138442712/56b76872-6943-43ae-b9c4-ba2f7cc0ee91)

**Comment by venxzw** [comment]
@bhzhu203 您好，我想请问一下，环境变量全部设置了还是出现了如下的报错：
![4DPXG4UI5HBGZ8$_2HKT1](https://github.com/Jittor/JittorLLMs/assets/138442712/80f096ed-65ab-459f-bd1a-edb0f6f89220)
