### ISSUE TITLE
不能正常申请CUDA内存

### ISSUE THREAD

**Issue by KCN-judu** [Jittor/JittorLLMs#86]
运行环境：
WindowsServer2019 
Intel(R) Xeno(R) CPU E5-2686 v4 @2.30GHz 2.29GHz (2个处理器) 
128GB RAM 
RTX2080Ti
12T HDD
```
尝试调整内存和显存限制后依旧出现爆内存/显存的问题，在跳出Traceback之前获取到如下信息：
[w 0504 02:52:44.996000 68 cuda_device_allocator.cc:30] Unable to alloc cuda device memory, use unify memory instead. This may cause low performance.
[i 0504 02:52:44.996000 68 cuda_device_allocator.cc:32]
=== display_memory_info ===
 total_cpu_ram:    15 B total_device_ram:    11GB
 hold_vars: 500 lived_vars: 547 lived_ops: 135
 jtorch_grad_vars: 0
 name: sfrl is_device: 1 used: 9.652GB(100%) unused:  1002KB(0.0099%) total: 9.653GB
 name: sfrl is_device: 1 used:     0 B(0%) unused:     1MB(100%) total:     1MB
 name: sfrl is_device: 0 used:     0 B(0%) unused:     1MB(100%) total:     1MB
 name: sfrl is_device: 0 used: 3.149GB(24.6%) unused: 9.652GB(75.4%) total:  12.8GB
 name: temp is_device: 0 used:     0 B(-nan(ind)%) unused:     0 B(-nan(ind)%) total:     0 B
 name: temp is_device: 1 used:     0 B(-nan(ind)%) unused:     0 B(-nan(ind)%) total:     0 B
 cpu&gpu: 22.46GB gpu: 9.654GB cpu:  12.8GB
 free: cpu(    0 B) gpu(    0 B)
 swap: total(    0 B) last(    0 B)
===========================

[w 0504 02:52:45.119000 68 cuda_device_allocator.cc:30] Unable to alloc cuda device memory, use unify memory instead. This may cause low performance.
[i 0504 02:52:45.120000 68 cuda_device_allocator.cc:32]
=== display_memory_info ===
 total_cpu_ram:    15 B total_device_ram:    11GB
 hold_vars: 500 lived_vars: 547 lived_ops: 135
 jtorch_grad_vars: 0
 name: sfrl is_device: 1 used: 9.652GB(100%) unused:  1002KB(0.0099%) total: 9.653GB
 name: sfrl is_device: 1 used:     0 B(0%) unused:     1MB(100%) total:     1MB
 name: sfrl is_device: 0 used:     0 B(0%) unused:     1MB(100%) total:     1MB
 name: sfrl is_device: 0 used: 3.149GB(24.6%) unused: 9.652GB(75.4%) total:  12.8GB
 name: temp is_device: 0 used:     0 B(-nan(ind)%) unused:     0 B(-nan(ind)%) total:     0 B
 name: temp is_device: 1 used:     0 B(-nan(ind)%) unused:     0 B(-nan(ind)%) total:     0 B
 cpu&gpu: 22.46GB gpu: 9.654GB cpu:  12.8GB
 free: cpu(    0 B) gpu(    0 B)
 swap: total(    0 B) last(    0 B)
===========================
```

**Comment by JianquanWang** [comment]
Same occurred to me
[w 0511 17:57:07.446000 88 cuda_device_allocator.cc:30] Unable to alloc cuda device memory, use unify memory instead. This may cause low performance.                                                                                           [i 0511 17:57:07.446000 88 cuda_device_allocator.cc:32]                                                                 === display_memory_info ===                                                                                              total_cpu_ram:    15 B total_device_ram: 11.99GB                                                                        hold_vars: 520 lived_vars: 567 lived_ops: 135                                                                           jtorch_grad_vars: 0                                                                                                     name: sfrl is_device: 1 used: 11.15GB(100%) unused:   324KB(0.00277%) total: 11.15GB                                    name: sfrl is_device: 1 used:     0 B(0%) unused:     1MB(100%) total:     1MB                                          name: sfrl is_device: 0 used:     0 B(0%) unused:     1MB(100%) total:     1MB                                          name: sfrl is_device: 0 used: 1.649GB(12.9%) unused: 11.15GB(87.1%) total:  12.8GB                                      name: temp is_device: 0 used:     0 B(-nan(ind)%) unused:     0 B(-nan(ind)%) total:     0 B                            name: temp is_device: 1 used:     0 B(-nan(ind)%) unused:     0 B(-nan(ind)%) total:     0 B                            cpu&gpu: 23.96GB gpu: 11.15GB cpu:  12.8GB                                                                              free: cpu(    0 B) gpu(    0 B)                                                                                         swap: total(    0 B) last(    0 B)                                                                                     ===========================                                                                                                                                                                                                                     [w 0511 17:57:07.491000 88 cuda_device_allocator.cc:30] Unable to alloc cuda device memory, use unify memory instead. This may cause low performance.                                                                                           [i 0511 17:57:07.492000 88 cuda_device_allocator.cc:32]                                                                 === display_memory_info ===                                                                                              total_cpu_ram:    15 B total_device_ram: 11.99GB                                                                        hold_vars: 520 lived_vars: 567 lived_ops: 135                                                                           jtorch_grad_vars: 0                                                                                                     name: sfrl is_device: 1 used: 11.15GB(100%) unused:   324KB(0.00277%) total: 11.15GB                                    name: sfrl is_device: 1 used:     0 B(0%) unused:     1MB(100%) total:     1MB                                          name: sfrl is_device: 0 used:     0 B(0%) unused:     1MB(100%) total:     1MB                                          name: sfrl is_device: 0 used: 1.649GB(12.9%) unused: 11.15GB(87.1%) total:  12.8GB                                      name: temp is_device: 0 used:     0 B(-nan(ind)%) unused:     0 B(-nan(ind)%) total:     0 B                            name: temp is_device: 1 used:     0 B(-nan(ind)%) unused:     0 B(-nan(ind)%) total:     0 B                            cpu&gpu: 23.96GB gpu: 11.15GB cpu:  12.8GB                                                                              free: cpu(    0 B) gpu(    0 B)                                                                                         swap: total(    0 B) last(    0 B)                                                                                     ===========================

**Comment by 1wpc** [comment]
我也遇到这个问题了

**Comment by 1wpc** [comment]
我已经解决了，运行模型时在管理员模式运行

**Comment by HJT9328** [comment]
问一下怎么解决的  我在管理员的情况下还是一样的

**Comment by 1wpc** [comment]
@HJT9328 那你就在图形界面中设置环境变量试试。从控制面板中进入编辑系统环境变量
<img width="482" alt="image" src="https://github.com/Jittor/JittorLLMs/assets/93064853/75de5a19-8381-4f47-929e-e54ed73522df">
新建一个变量，按照官方文档的命名。
