### ISSUE TITLE
运行python cli_demo.py [chatglm|pangualpha|llama|chatrwkv]时出错

### ISSUE THREAD

**Issue by zhoushiyoung** [Jittor/JittorLLMs#89]
运行python cli_demo.py [chatglm|pangualpha|llama|chatrwkv]时
报错：'pangualpha' is not recognized as an internal or external command,
operable program or batch file.

**Comment by zhoushiyoung** [comment]
我自己懂了，原来是这里面选一个运行，搞得我以为这个是安装公用包的

**Comment by 66ling66** [comment]
请问选择的格式是什么样子
