### ISSUE TITLE
macos13无法运行，提示这个报错

### ISSUE THREAD

**Issue by 0013227** [Jittor/JittorLLMs#98]
<img width="563" alt="截屏2023-05-07 16 35 59" src="https://user-images.githubusercontent.com/93069353/236666955-234a53a1-22bf-47d5-bf22-6f6d4eda18a8.png">
macos13无法运行，提示这个报错

**Comment by 0013227** [comment]
(JittorLLMs) weitianrui@weitianruideMacBook-Pro JittorLLMs % python web_demo.py chatglm
[i 0507 16:34:19.863963 32 lock.py:85] Create lock file:/Users/weitianrui/.cache/jittor/jt1.3.7/clang14.0.3/py3.8.16/macOS-10.16-x8xc1/IntelRCoreTMi5xf3/jittor.lock
[i 0507 16:34:19.882656 32 compiler.py:955] Jittor(1.3.7.15) src: /usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor
[i 0507 16:34:19.919488 32 compiler.py:956] clang at /usr/bin/clang++(14.0.3)
[i 0507 16:34:19.919769 32 compiler.py:957] cache_path: /Users/weitianrui/.cache/jittor/jt1.3.7/clang14.0.3/py3.8.16/macOS-10.16-x8xc1/IntelRCoreTMi5xf3/default
[i 0507 16:34:20.020869 32 compiler.py:34] Create cache dir: /Users/weitianrui/.cache/jittor/jt1.3.7/clang14.0.3/py3.8.16/macOS-10.16-x8xc1/IntelRCoreTMi5xf3/default/jit
[i 0507 16:34:20.021269 32 compiler.py:34] Create cache dir: /Users/weitianrui/.cache/jittor/jt1.3.7/clang14.0.3/py3.8.16/macOS-10.16-x8xc1/IntelRCoreTMi5xf3/default/obj_files
[i 0507 16:34:20.021504 32 compiler.py:34] Create cache dir: /Users/weitianrui/.cache/jittor/jt1.3.7/clang14.0.3/py3.8.16/macOS-10.16-x8xc1/IntelRCoreTMi5xf3/default/gen
[i 0507 16:34:20.021757 32 compiler.py:34] Create cache dir: /Users/weitianrui/.cache/jittor/jt1.3.7/clang14.0.3/py3.8.16/macOS-10.16-x8xc1/IntelRCoreTMi5xf3/default/tmp
[i 0507 16:34:20.022012 32 compiler.py:34] Create cache dir: /Users/weitianrui/.cache/jittor/jt1.3.7/clang14.0.3/py3.8.16/macOS-10.16-x8xc1/IntelRCoreTMi5xf3/default/checkpoints
In file included from /usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/cache_compile.cc:12:
In file included from /usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/misc/hash.h:8:
In file included from /usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/common.h:10:
/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/log.h:138:18: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
        send_log(move(out), level, verbose);
                 ^
                 std::
1 warning generated.
In file included from /usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/log.cc:14:
/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/log.h:138:18: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
        send_log(move(out), level, verbose);
                 ^
                 std::
/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/log.cc:195:12: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
    return move(logs);
           ^
           std::
/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/log.cc:376:19: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
    vprefix_map = move(new_map);
                  ^
                  std::
3 warnings generated.
In file included from /usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/tracer.cc:11:
In file included from /usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/tracer.h:8:
In file included from /usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/common.h:10:
/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/log.h:138:18: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
        send_log(move(out), level, verbose);
                 ^
                 std::
/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/tracer.cc:49:9: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
        sprintf(pid_buf, "%d", getpid());
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/tracer.cc:145:9: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
        sprintf(pid_buf, "%d", getpid());
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/tracer.cc:147:9: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
        sprintf(st_buf, "set backtrace limit %d", trace_depth);
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/tracer.cc:213:13: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
            sprintf(syscom,"%s %p -f -p -i -e %.*s", addr2line_path.c_str(), trace[i], p, messages[i]);
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
5 warnings generated.
In file included from /usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/jit_utils.cc:7:
In file included from /usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/cache_compile.h:8:
In file included from /usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/common.h:10:
/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/log.h:138:18: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
        send_log(move(out), level, verbose);
                 ^
                 std::
In file included from /usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/jit_utils.cc:8:
In file included from /usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/pyjt/py_converter.h:17:
/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/profiler/simple_profiler.h:48:48: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
    inline SimpleProfiler(string&& name): name(move(name)), cnt(0), total_ns(0), sum(0) {}
                                               ^
                                               std::
In file included from /usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/jit_utils.cc:8:
/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/pyjt/py_converter.h:358:16: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
        return move(fetch_sync({ptr}).at(0));
               ^
               std::
/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/jit_utils.cc:505:37: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
                return to_py_object(move(ret));
                                    ^
                                    std::
4 warnings generated.
In file included from /usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/str_utils.cc:8:
In file included from /usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/str_utils.h:8:
In file included from /usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/common.h:10:
/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/log.h:138:18: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
        send_log(move(out), level, verbose);
                 ^
                 std::
1 warning generated.
ld: library not found for -lomp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "web_demo.py", line 26, in <module>
    model = models.get_model(args)
  File "/Users/weitianrui/JittorLLMs/models/__init__.py", line 38, in get_model
    globals()[f"get_{model_name}"]()
  File "/Users/weitianrui/JittorLLMs/models/util.py", line 51, in get_chatglm
    new_path.append(download_fromhub(f"jittorhub://{f}", tdir="chat-glm"))
  File "/Users/weitianrui/JittorLLMs/models/util.py", line 5, in download_fromhub
    import jittor as jt
  File "/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/compiler.py", line 1189, in <module>
    check_cache_compile()
  File "/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/compiler.py", line 884, in check_cache_compile
    recompile = compile(cc_path, cc_flags+f" {opt_flags} ", files, jit_utils.cache_path+'/jit_utils_core'+extension_suffix, True)
  File "/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/compiler.py", line 126, in compile
    return do_compile(fix_cl_flags(cmd))
  File "/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/compiler.py", line 91, in do_compile
    run_cmd(cmd)
  File "/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor_utils/__init__.py", line 188, in run_cmd
    raise Exception(err_msg)
Exception: Run cmd failed: "/usr/bin/clang++" "/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/cache_compile.cc" "/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/log.cc" "/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/tracer.cc" "/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/jit_utils.cc" "/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src/utils/str_utils.cc"   -Wall -Wno-unknown-pragmas -std=c++14 -fPIC  -march=native  -fdiagnostics-color=always  -undefined dynamic_lookup -lomp  -L/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib -Wl,-rpath,/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib  -lstdc++ -ldl -shared  -I"/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/lib/python3.8/site-packages/jittor/src" -I/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/include/python3.8 -I/usr/local/Caskroom/miniconda/base/envs/JittorLLMs/include/python3.8  -O2   -o "/Users/weitianrui/.cache/jittor/jt1.3.7/clang14.0.3/py3.8.16/macOS-10.16-x8xc1/IntelRCoreTMi5xf3/default/jit_utils_core.cpython-38-darwin.so"
(JittorLLMs) weitianrui@weitianruideMacBook-Pro JittorLLMs %

**Comment by lzhengning** [comment]
please read the [installation requirements](https://github.com/jittor/jittor#macos-install).
